version: "3.8"
services:
    reac-app:
        stdin_open: true
        tty: true
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/code
            - /code/node_modules
        environment:
            - "./.env"
